name: ci-macos

env:
  CI: GITHUB

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
  schedule:
    - cron: "42 3 * * *"
      timezone: "Europe/Moscow"
  repository_dispatch:
    types: [dispatch-event]

jobs:
  ci-job:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v7
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: true
    - name: build-stat-info
      shell: bash
      run: |
        cmake -S . -B @ci-cmake-build -DCMAKE_BUILD_TYPE=Release -DMDBX_BUILD_CXX:BOOL=ON \
          -DMDBX_ENABLE_TESTS=ON
        cmake --build @ci-cmake-build --target ut_stat-info -j2
    - name: run-stat-info
      shell: bash
      run: |
        ./@ci-cmake-build/ut_stat-info --gtest_filter=ut_stat_info.sysraminfo